name: Deploy Spring Boot to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17 for building the project
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build the project with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Copy JAR file to EC2 instance
      - name: Copy JAR to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          scp -o StrictHostKeyChecking=no -i private_key.pem target/ProjectGreenie-0.0.1-SNAPSHOT.jar ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/

      # Run Spring Boot App on EC2
      - name: Run Spring Boot App on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'

          echo ">>> Stopping any running instance of the app..."
          sudo pkill -f 'ProjectGreenie-0.0.1-SNAPSHOT.jar' || true

          echo ">>> Ensuring directory exists for application properties"
          sudo mkdir -p /opt/greenie-config

          echo ">>> Writing MongoDB URI to application.properties"
          echo "spring.data.mongodb.uri=${{ secrets.MONGODB_URI }}" | sudo tee /opt/greenie-config/application.properties
          echo "spring.data.mongodb.database=greenie_db" | sudo tee -a /opt/greenie-config/application.properties
          echo "spring.data.mongodb.auto-index-creation=true" | sudo tee -a /opt/greenie-config/application.properties

          echo ">>> Granting execute permissions to JAR"
          chmod +x /home/ubuntu/ProjectGreenie-0.0.1-SNAPSHOT.jar

          echo ">>> Starting Spring Boot application..."
          nohup java -jar /home/ubuntu/ProjectGreenie-0.0.1-SNAPSHOT.jar --spring.config.location=file:/opt/greenie-config/application.properties > /home/ubuntu/log.txt 2>&1 &

          sleep 5  # Give time for the app to start

          echo ">>> Checking if the application is running..."
          pgrep -f 'ProjectGreenie-0.0.1-SNAPSHOT.jar' && echo "✅ App is running!" || echo "❌ App failed to start!"
          EOF

      # Clean up the private key after deployment
      - name: Clean up private key
        run: rm -f private_key.pem
