# Run Spring Boot App on EC2
- name: Run Spring Boot App on EC2
  run: |
    ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
    
    echo ">>> Stopping any running instance of the app..."
    sudo pkill -f 'ProjectGreenie-0.0.1-SNAPSHOT.jar' || true

    # Optional: Set up environment variable for MongoDB URI
    echo "export MONGODB_URI=${{ secrets.MONGODB_URI }}" >> ~/.bashrc
    source ~/.bashrc

    # Optional: Write MongoDB URI to application properties
    sudo mkdir -p /opt/greenie-config
    echo "spring.data.mongodb.uri=$MONGODB_URI" | sudo tee /opt/greenie-config/application.properties
    echo "spring.data.mongodb.database=greenie_db" | sudo tee -a /opt/greenie-config/application.properties
    echo "spring.data.mongodb.auto-index-creation=true" | sudo tee -a /opt/greenie-config/application.properties

    echo ">>> Granting execute permissions to JAR"
    chmod +x /home/ubuntu/ProjectGreenie-0.0.1-SNAPSHOT.jar

    echo ">>> Starting Spring Boot application..."
    nohup java -jar /home/ubuntu/ProjectGreenie-0.0.1-SNAPSHOT.jar --spring.data.mongodb.uri="${MONGODB_URI}" > /home/ubuntu/log.txt 2>&1 &

    sleep 5  # Give time for the app to start

    echo ">>> Checking if the application is running..."
    pgrep -f 'ProjectGreenie-0.0.1-SNAPSHOT.jar' && echo "✅ App is running!" || echo "❌ App failed to start!"
    EOF
