jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Create .env file with MongoDB URI
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env
          echo "Other environment variables can go here if necessary" >> .env

      - name: Copy JAR to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          scp -o StrictHostKeyChecking=no -i private_key.pem target/ProjectGreenie-0.0.1-SNAPSHOT.jar ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/

      - name: Run Spring Boot App on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          # Create .env file with MongoDB URI on EC2 (if needed)
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > /home/ubuntu/.env
          sudo pkill -f 'ProjectGreenie-0.0.1-SNAPSHOT.jar' || true
          chmod +x /home/ubuntu/ProjectGreenie-0.0.1-SNAPSHOT.jar
          nohup java -jar /home/ubuntu/ProjectGreenie-0.0.1-SNAPSHOT.jar > /home/ubuntu/log.txt 2>&1 &
          EOF
